"""Tests for the feedback loop.

This is the only signal generated by the person being recommended to, so
the things worth pinning down are that a vote is recorded, that it
changes the ranking, and that a film someone rejected never comes back.
"""
import sqlite3

import pytest

from src import cache, config, feedback

USER = "pytest-user"


@pytest.fixture(autouse=True)
def clean_votes():
    def wipe():
        conn = sqlite3.connect(config.CACHE_DB)
        conn.execute("DELETE FROM feedback WHERE user_id = ?", (USER,))
        conn.commit()
        conn.close()
    wipe()
    yield
    wipe()


def _cached_ids(limit=3):
    """A few film ids that are definitely in the local cache."""
    return [m["id"] for m in cache.all_movies()[:limit]]


def test_a_vote_is_recorded_and_can_be_changed():
    (movie_id,) = _cached_ids(1)
    feedback.record(USER, movie_id, 1)
    assert cache.get_feedback(USER) == {movie_id: 1}

    feedback.record(USER, movie_id, -1)
    assert cache.get_feedback(USER) == {movie_id: -1}, "re-voting should replace"


def test_votes_alone_build_a_profile_without_letterboxd():
    """Personalisation must not require linking an account."""
    up, down = _cached_ids(2)
    feedback.record(USER, up, 1)
    feedback.record(USER, down, -1)

    fragment = feedback.profile_fragment(USER)
    assert fragment is not None
    assert [f["id"] for f in fragment["liked"]] == [up]
    assert [f["id"] for f in fragment["disliked"]] == [down]
    assert fragment["liked"][0]["rating"] == feedback.UP_RATING
    assert fragment["disliked"][0]["rating"] == feedback.DOWN_RATING


def test_no_votes_means_no_fragment():
    assert feedback.profile_fragment(USER) is None


def test_merge_keeps_votes_ahead_of_letterboxd_history():
    """MAX_LIKED_FILMS truncates, and a direct verdict should survive it."""
    (voted,) = _cached_ids(1)
    feedback.record(USER, voted, 1)
    fragment = feedback.profile_fragment(USER)

    base = {
        "liked": [{"title": f"Old Film {i}", "year": "2001", "rating": 4.0}
                  for i in range(config.MAX_LIKED_FILMS + 10)],
        "disliked": [],
        "watched_keys": {("old film 0", "2001")},
    }
    merged = feedback.merge(base, fragment)

    assert merged["liked"][0]["id"] == voted
    assert len(merged["liked"]) <= config.MAX_LIKED_FILMS


def test_merge_tolerates_either_side_missing():
    assert feedback.merge(None, None) is None
    base = {"liked": [], "disliked": [], "watched_keys": set()}
    assert feedback.merge(base, None) is base


def test_a_voted_film_counts_as_seen():
    """Whichever way they voted, they've now been shown it."""
    up, down = _cached_ids(2)
    feedback.record(USER, up, 1)
    feedback.record(USER, down, -1)

    fragment = feedback.profile_fragment(USER)
    titles = {k[0] for k in fragment["watched_keys"]}
    for movie_id in (up, down):
        assert cache.get_cached(movie_id)["title"].lower().strip() in titles


def test_summary_reads_back_the_counts():
    up, down = _cached_ids(2)
    assert feedback.summary(USER) == "no ratings yet"
    feedback.record(USER, up, 1)
    feedback.record(USER, down, -1)
    assert feedback.summary(USER) == "1 👍, 1 👎"


# --------------------------------------------------------------------------
# the button encoding
# --------------------------------------------------------------------------

def test_vote_buttons_fit_telegrams_callback_limit():
    from src.bot import _vote_keyboard

    keyboard = _vote_keyboard([
        {"id": 157336, "title": "Interstellar"},
        {"id": 286217, "title": "A Very Long Film Title That Goes On And On"},
    ])
    buttons = [b for row in keyboard.inline_keyboard for b in row]
    assert len(buttons) == 4
    for button in buttons:
        assert len(button.callback_data.encode()) <= 64


def test_vote_buttons_are_skipped_for_films_with_no_id():
    from src.bot import _vote_keyboard

    assert _vote_keyboard([{"title": "No Id Here"}]) is None


def test_vote_callback_data_round_trips():
    from src.bot import VOTE_PREFIX, _vote_keyboard

    keyboard = _vote_keyboard([{"id": 999, "title": "X"}])
    up, down = keyboard.inline_keyboard[0]
    for button, expected in ((up, 1), (down, -1)):
        prefix, verdict, movie_id = button.callback_data.split(":")
        assert prefix == VOTE_PREFIX
        assert int(verdict) == expected
        assert int(movie_id) == 999


# --------------------------------------------------------------------------
# the loop actually closing
# --------------------------------------------------------------------------

def test_a_rejected_film_is_never_recommended_again():
    """The point of a thumbs-down: it has to stick."""
    import numpy as np
    from sklearn.preprocessing import normalize

    from src.signals import Signal
    from src.taste import fit_vectorizer, build_soup, recommend

    films = cache.all_movies()[:40]
    if len(films) < 20:
        pytest.skip("local cache too small for this test")

    weights = config.SOUP_WEIGHTS
    vectorizer, matrix = fit_vectorizer([build_soup(f, weights) for f in films])
    signal = Signal(normalize(np.asarray(matrix.todense(), dtype=np.float32)),
                    movies=list(films))
    signal.name = "metadata"

    seed = films[0]
    before = recommend(reference_features=[seed], signal=signal,
                       top_n=5, min_z=-10.0)
    assert before, "expected some picks to reject"

    rejected = before[0]
    feedback.record(USER, rejected["id"], -1)

    from src.recommender import build_profile
    after = recommend(profile=build_profile(None, USER),
                      reference_features=[seed], signal=signal,
                      top_n=5, min_z=-10.0)
    assert rejected["id"] not in [p["id"] for p in after]
