"""SQLite-backed feature cache.

The old version held the whole cache in one dict and rewrote the entire
JSON file on every miss, which is O(n^2) writes while building a candidate
pool. It also handed out live references to its own dict, so anything that
added a key to a returned feature dict (rank_candidates adds "score")
silently persisted that key on the next save.

Both are fixed here: writes are per-row, and reads return a copy.
"""
import json
import logging
import sqlite3
import threading
import time

from src import config
from src.tmdb import FEATURE_VERSION, SEARCH_VERSION, get_movie_features

log = logging.getLogger(__name__)

_lock = threading.Lock()


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(config.CACHE_DB, check_same_thread=False)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute(
        "CREATE TABLE IF NOT EXISTS movies ("
        "  id INTEGER PRIMARY KEY,"
        "  data TEXT NOT NULL,"
        "  fetched_at REAL NOT NULL)"
    )
    # Title -> TMDB id. Resolving a profile means one search per film, and
    # those lookups never change, so caching them takes the personalised
    # path from ~25 network round trips to zero on a repeat request.
    conn.execute(
        "CREATE TABLE IF NOT EXISTS searches ("
        "  query TEXT NOT NULL,"
        "  year TEXT NOT NULL DEFAULT '',"
        "  movie_id INTEGER,"
        "  v INTEGER NOT NULL DEFAULT 1,"
        "  PRIMARY KEY (query, year))"
    )
    # Older databases predate the version column.
    columns = {row[1] for row in conn.execute("PRAGMA table_info(searches)")}
    if "v" not in columns:
        conn.execute("ALTER TABLE searches ADD COLUMN v INTEGER NOT NULL DEFAULT 1")
    # TMDB's own "recommendations" for a film, which are derived from
    # what its users actually watch together. One row per film, so the
    # graph can be rebuilt without re-fetching 5,000 pages.
    conn.execute(
        "CREATE TABLE IF NOT EXISTS recommendations ("
        "  movie_id INTEGER PRIMARY KEY,"
        "  rec_ids TEXT NOT NULL,"
        "  fetched_at REAL NOT NULL)"
    )
    # Thumbs up / down on individual recommendations. This is the only
    # signal in the system generated by the person being recommended to,
    # and the only one that improves with use - everything else is a
    # fixed property of the films.
    conn.execute(
        "CREATE TABLE IF NOT EXISTS feedback ("
        "  user_id TEXT NOT NULL,"
        "  movie_id INTEGER NOT NULL,"
        "  verdict INTEGER NOT NULL,"
        "  created_at REAL NOT NULL,"
        "  PRIMARY KEY (user_id, movie_id))"
    )
    # Letterboxd scrapes are the slowest thing in a request (a third-party
    # page load, then one TMDB resolution per film). Caching the finished
    # profile is what turns a repeat /rec from ~30s into instant.
    conn.execute(
        "CREATE TABLE IF NOT EXISTS profiles ("
        "  username TEXT PRIMARY KEY,"
        "  data TEXT NOT NULL,"
        "  fetched_at REAL NOT NULL)"
    )
    return conn


_conn = _connect()


def _migrate_legacy_json() -> None:
    """One-time import of the old data/features_cache.json."""
    if not config.LEGACY_CACHE_JSON.exists():
        return
    with _lock:
        already = _conn.execute("SELECT COUNT(*) FROM movies").fetchone()[0]
    if already:
        return

    with open(config.LEGACY_CACHE_JSON) as f:
        legacy = json.load(f)

    now = time.time()
    rows = []
    for key, features in legacy.items():
        features.pop("score", None)          # drop any previously leaked field
        features.setdefault("id", int(key))
        rows.append((int(key), json.dumps(features), now))

    with _lock:
        _conn.executemany(
            "INSERT OR REPLACE INTO movies (id, data, fetched_at) VALUES (?, ?, ?)", rows
        )
        _conn.commit()
    log.info("migrated %d movies from features_cache.json into SQLite", len(rows))


_migrate_legacy_json()


def get_cached(movie_id: int) -> dict | None:
    with _lock:
        row = _conn.execute("SELECT data FROM movies WHERE id = ?", (movie_id,)).fetchone()
    return json.loads(row[0]) if row else None


def put(movie_id: int, features: dict) -> None:
    with _lock:
        _conn.execute(
            "INSERT OR REPLACE INTO movies (id, data, fetched_at) VALUES (?, ?, ?)",
            (movie_id, json.dumps(features), time.time()),
        )
        _conn.commit()


def is_current(features: dict | None) -> bool:
    """Was this row written by the current feature schema?

    A row cached before the schema was widened has no overview terms,
    writers or collection, so it would sit in the corpus as an unfairly
    short vector next to the rich ones. Treat it as a miss.
    """
    return bool(features) and features.get("_v") == FEATURE_VERSION


def cached_features(movie_id: int) -> dict:
    """Return features for a movie, fetching from TMDB on a miss.

    Always returns a fresh dict, so callers may annotate it freely.
    """
    hit = get_cached(movie_id)
    if is_current(hit):
        return hit

    log.info("cache %s - fetching %s from TMDB",
             "STALE" if hit else "MISS", movie_id)
    features = get_movie_features(movie_id)
    put(movie_id, features)
    return features


def cached_features_many(movie_ids: list[int]) -> list[dict]:
    """Bulk variant: one query for the hits, then fetch only the misses."""
    ids = list(dict.fromkeys(int(m) for m in movie_ids))
    if not ids:
        return []

    placeholders = ",".join("?" * len(ids))
    with _lock:
        rows = _conn.execute(
            f"SELECT id, data FROM movies WHERE id IN ({placeholders})", ids
        ).fetchall()

    found = {row[0]: json.loads(row[1]) for row in rows}
    found = {k: v for k, v in found.items() if is_current(v)}

    for movie_id in ids:
        if movie_id not in found:
            try:
                found[movie_id] = cached_features(movie_id)
            except Exception as exc:            # one bad id shouldn't kill the pool
                log.warning("skipping movie %s: %s", movie_id, exc)

    return [found[m] for m in ids if m in found]


def cached_search(title: str, year: str = None) -> tuple[bool, int | None]:
    """Look up a cached title->id resolution.

    Returns (was_cached, movie_id). movie_id may be None for a title that
    genuinely has no TMDB match - that negative result is worth caching too.
    """
    with _lock:
        row = _conn.execute(
            "SELECT movie_id FROM searches WHERE query = ? AND year = ? AND v = ?",
            (title.lower().strip(), year or "", SEARCH_VERSION),
        ).fetchone()
    return (True, row[0]) if row else (False, None)


def put_search(title: str, year: str, movie_id: int | None) -> None:
    with _lock:
        _conn.execute(
            "INSERT OR REPLACE INTO searches (query, year, movie_id, v) "
            "VALUES (?, ?, ?, ?)",
            (title.lower().strip(), year or "", movie_id, SEARCH_VERSION),
        )
        _conn.commit()


def all_movies(current_only: bool = True) -> list[dict]:
    """Every cached movie - the corpus the model is fitted on."""
    with _lock:
        rows = _conn.execute("SELECT data FROM movies").fetchall()
    movies = [json.loads(r[0]) for r in rows]
    return [m for m in movies if is_current(m)] if current_only else movies


def count(current_only: bool = False) -> int:
    if not current_only:
        with _lock:
            return _conn.execute("SELECT COUNT(*) FROM movies").fetchone()[0]
    return len(all_movies(current_only=True))


def stale_ids() -> list[int]:
    """Cached movies still on an older feature schema."""
    with _lock:
        rows = _conn.execute("SELECT id, data FROM movies").fetchall()
    return [r[0] for r in rows if not is_current(json.loads(r[1]))]


# --------------------------------------------------------------------------
# Letterboxd profiles
# --------------------------------------------------------------------------

def get_cached_profile(username: str, max_age: float = None) -> dict | None:
    """A previously scraped profile, if it is still fresh enough."""
    max_age = config.PROFILE_TTL if max_age is None else max_age
    with _lock:
        row = _conn.execute(
            "SELECT data, fetched_at FROM profiles WHERE username = ?",
            (username.lower().strip(),),
        ).fetchone()
    if not row or (time.time() - row[1]) > max_age:
        return None

    profile = json.loads(row[0])
    # watched_keys round-trips through JSON as a list of pairs.
    profile["watched_keys"] = {tuple(k) for k in profile.get("watched_keys", [])}
    return profile


def put_profile(username: str, profile: dict) -> None:
    serialisable = dict(profile)
    serialisable["watched_keys"] = [list(k) for k in profile.get("watched_keys", set())]
    with _lock:
        _conn.execute(
            "INSERT OR REPLACE INTO profiles (username, data, fetched_at) VALUES (?, ?, ?)",
            (username.lower().strip(), json.dumps(serialisable), time.time()),
        )
        _conn.commit()


def get_recommendations(movie_id: int) -> list | None:
    with _lock:
        row = _conn.execute(
            "SELECT rec_ids FROM recommendations WHERE movie_id = ?",
            (int(movie_id),)).fetchone()
    return json.loads(row[0]) if row else None


def put_recommendations(movie_id: int, rec_ids: list) -> None:
    with _lock:
        _conn.execute(
            "INSERT OR REPLACE INTO recommendations (movie_id, rec_ids, fetched_at) "
            "VALUES (?, ?, ?)",
            (int(movie_id), json.dumps([int(r) for r in rec_ids]), time.time()))
        _conn.commit()


def all_recommendations() -> dict:
    with _lock:
        rows = _conn.execute("SELECT movie_id, rec_ids FROM recommendations").fetchall()
    return {int(r[0]): json.loads(r[1]) for r in rows}


# --------------------------------------------------------------------------
# recommendation feedback
# --------------------------------------------------------------------------

def put_feedback(user_id: str, movie_id: int, verdict: int) -> None:
    """Record a thumbs up (+1) or down (-1). Re-voting replaces."""
    with _lock:
        _conn.execute(
            "INSERT OR REPLACE INTO feedback "
            "(user_id, movie_id, verdict, created_at) VALUES (?, ?, ?, ?)",
            (str(user_id), int(movie_id), int(verdict), time.time()))
        _conn.commit()


def get_feedback(user_id: str) -> dict:
    """movie_id -> verdict for one user."""
    with _lock:
        rows = _conn.execute(
            "SELECT movie_id, verdict FROM feedback WHERE user_id = ?",
            (str(user_id),)).fetchall()
    return {int(r[0]): int(r[1]) for r in rows}


def feedback_counts(user_id: str) -> tuple[int, int]:
    votes = get_feedback(user_id)
    up = sum(1 for v in votes.values() if v > 0)
    return up, len(votes) - up


def profile_age(username: str) -> float | None:
    """Seconds since this profile was scraped, or None if never."""
    with _lock:
        row = _conn.execute(
            "SELECT fetched_at FROM profiles WHERE username = ?",
            (username.lower().strip(),),
        ).fetchone()
    return (time.time() - row[0]) if row else None
