"""Turning thumbs up/down on recommendations into a taste signal.

Every other signal in this system is a fixed property of the films:
metadata does not change, embeddings do not change, and the MovieLens
factors are a 2015 snapshot. Feedback is the only one that is about the
person, generated by the person, and better tomorrow than today.

It is also, by construction, independent of everything else - which is
the property that decided whether a signal was worth blending. A film the
user rejected was, by definition, one the content signals had ranked
highly, so their verdict carries information no content signal has.

Two things happen with a vote:

  * it joins the taste profile, weighted at the extremes, so it pulls
    ranking toward what they endorsed and away from what they rejected;
  * the film is marked seen, so it is never recommended again.

A user with no Letterboxd account builds a profile purely this way, which
means personalisation no longer requires linking anything.
"""
import logging

from src import cache, config

log = logging.getLogger(__name__)

# A vote is a direct statement about a film we put in front of them, so
# it sits at the extremes of the rating scale rather than in the middle
# of it. `_rating_weight` maps 5.0 to 2.5 and 0.5 to its 0.1 floor.
UP_RATING = 5.0
DOWN_RATING = 0.5


def record(user_id: str, movie_id: int, verdict: int) -> None:
    cache.put_feedback(user_id, movie_id, verdict)


def _entry(movie_id: int, rating: float) -> dict | None:
    """A profile entry for a voted film, from whatever we already cached."""
    features = cache.get_cached(movie_id)
    if not features or not features.get("title"):
        return None
    return {
        "title":  features["title"],
        "year":   features.get("year") or None,
        "rating": rating,
        "id":     movie_id,
    }


def profile_fragment(user_id: str) -> dict | None:
    """A taste profile built only from this user's votes."""
    votes = cache.get_feedback(user_id)
    if not votes:
        return None

    liked, disliked, seen = [], [], set()
    for movie_id, verdict in votes.items():
        entry = _entry(movie_id, UP_RATING if verdict > 0 else DOWN_RATING)
        if entry is None:
            continue
        (liked if verdict > 0 else disliked).append(entry)
        seen.add((entry["title"].lower().strip(),
                  str(entry["year"]) if entry["year"] else None))

    if not liked and not disliked:
        return None

    return {
        "username":     None,
        "films":        liked + disliked,
        "liked":        liked,
        "disliked":     disliked,
        "watched_keys": seen,
        "total_films":  len(votes),
        "total_rated":  len(votes),
    }


def merge(base: dict | None, fragment: dict | None) -> dict | None:
    """Fold votes into a Letterboxd profile, votes first.

    Order matters: `MAX_LIKED_FILMS` truncates the liked list, and a
    direct verdict on something we recommended should outlive a
    four-star rating from two years ago when that cut is made.
    """
    if fragment is None:
        return base
    if base is None:
        return fragment

    def combine(from_votes, from_letterboxd):
        seen_ids = {f.get("id") for f in from_votes if f.get("id")}
        seen_titles = {(f["title"].lower().strip(),
                        str(f.get("year")) if f.get("year") else None)
                       for f in from_votes}
        extra = [f for f in from_letterboxd
                 if f.get("id") not in seen_ids
                 and (f["title"].lower().strip(),
                      str(f.get("year")) if f.get("year") else None) not in seen_titles]
        return (from_votes + extra)[:config.MAX_LIKED_FILMS]

    merged = dict(base)
    merged["liked"] = combine(fragment["liked"], base.get("liked", []))
    merged["disliked"] = combine(fragment["disliked"], base.get("disliked", []))
    merged["watched_keys"] = set(base.get("watched_keys", set())) | fragment["watched_keys"]
    return merged


def summary(user_id: str) -> str:
    up, down = cache.feedback_counts(user_id)
    if not up and not down:
        return "no ratings yet"
    return f"{up} 👍, {down} 👎"
